version: "3"
services:
  zookeeper_1:
    image: bitnami/zookeeper:latest
    container_name: zookeeper_1
    environment:
      ZOO_SERVER_ID: 1
      ZOO_SERVERS: zookeeper_1:2888:3888,0.0.0.0:2888:3888,zookeeper_3:2888:3888
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181"
      - "2888"
      - "3888"

  zookeeper_2:
    image: bitnami/zookeeper:latest
    container_name: zookeeper_2
    environment:
      ZOO_SERVER_ID: 2
      ZOO_SERVERS: zookeeper_1:2888:3888,0.0.0.0:2888:3888,zookeeper_3:2888:3888
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181"
      - "2888"
      - "3888"

  zookeeper_3:
    image: bitnami/zookeeper:latest
    container_name: zookeeper_3
    environment:
      ZOO_SERVER_ID: 3
      ZOO_SERVERS: zookeeper_1:2888:3888,0.0.0.0:2888:3888,zookeeper_3:2888:3888
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181"
      - "2888"
      - "3888"

  kafka_A:
    image: wurstmeister/kafka
    container_name: kafka_A
    depends_on:
      - zookeeper_1
      - zookeeper_2
      - zookeeper_3
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 192.168.50.247
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_1:2181,zookeeper_2:2181,zookeeper_3:2181
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3

  kafka_B:
    image: wurstmeister/kafka
    container_name: kafka_B
    depends_on:
      - zookeeper_1
      - zookeeper_2
      - zookeeper_3
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: 192.168.50.247
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_1:2181,zookeeper_2:2181,zookeeper_3:2181
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3

  kafka_C:
    image: wurstmeister/kafka
    container_name: kafka_C
    depends_on:
      - zookeeper_1
      - zookeeper_2
      - zookeeper_3
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: 192.168.50.247
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_1:2181,zookeeper_2:2181,zookeeper_3:2181
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3

  kafka-ui:
    image: obsidiandynamics/kafdrop
    container_name: kafka-web-ui
    environment:
      - KAFKA_BROKERCONNECT=kafka_A:9092,kafka_B:9093,kafka_C:9094
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - kafka_A
      - kafka_B
      - kafka_C
      - zookeeper_1
      - zookeeper_2
      - zookeeper_3